# Github action schedule name 'Schedule Jupyter Notebook'
name: Schedule Jupyter Notebook

# To control workflow schedule time
on: 
  # Allow running workflow manually
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Schedule to run every 60 minutes, testing first!

# Workflow run
jobs:
  # Contain a single job called 'run-notebook'
  run-notebook:
    # Type of runner to use to run the job
    runs-on: ubuntu-latest

    # Steps represent tasks that will be executed
    steps:
      - name: Repo
        uses: actions/checkout@v2 # Select an action

      - name: Python Setup
        uses: actions/setup-python@v2 # Select an action
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


############################################################

      # - name: Jupyter Notebook Execution
      #   run: |
      #     jupyter nbconvert --to html --execute EDA_Github_Action.ipynb
      #   shell: bash

      # - name: Save notebook HTML
      #   run: |
      #     mv EDA_Github_Action_html_read.html $GITHUB_WORKSPACE/EDA_Github_Action.html
      #   shell: bash


      # - name: Print from test.py
      #   run: |
      #      export INPUT_STORE=$(jupyter nbconvert --to html --execute EDA_Github_Action.ipynb)
      #      echo "Access direct: "
      #      echo $INPUT_STORE


      - name: Run Program
        run: |
          python3 EDA_Github_Action_2.0.py