name: Schedule Jupyter Notebook

# To control workflow schedule time
on: 
  # Allow running workflow manually
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Schedule to run every 5 minutes, testing first!

# Workflow run
jobs:
  # Contain a single job called 'run-notebook'
  run-notebook:
    # Type of runner to use to run the job
    runs-on: ubuntu-latest

    # Steps represent tasks that will be executed
    steps:
      - name: Repo
        uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  

      - name: Jupyter Notebook Execution
        run: jupyter nbconvert --execute EDA.ipynb  # Corrected typo 'jupyter execute'
        shell: bash
