# Github action schedule name 'Schedule Blood Donation'
name: Schedule Blood Donation

# To control workflow schedule time
on: 
  # Allow running workflow manually
  workflow_dispatch:
  schedule:
   # - cron: '45 22 * * *' # Schedule to run at 10:45pm UTC ~~ 06:45 am Malaysia!!! The runtime might be delay for +- few minutes
   #STOPPING THE JOB
   
# Workflow run
jobs:
  # Contain a single job called 'Run_EDA_Daily_Update'
  Run-EDA_Daily_Update:
    # Type of runner to use to run the job
    runs-on: ubuntu-latest

    # Steps represent tasks that will be executed
    steps:
      - name: Repo
        uses: actions/checkout@v2 # Select an action

      - name: Python Setup
        uses: actions/setup-python@v2 # Select an action
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Program
        run: |
          python3 EDA_Github_Action_2.py
